# :72:D3:28
substitutions:
  device_name: avery-desk-light
  friendly_name: Avery Desk Light
  device_description: Avery Desk Light (Plug)
  ip_address: 10.0.65.144
  # fold -bw32 </dev/urandom|head -n1|tr -d '\n'|base64
  api_key: "3VsqmtjJLb5BhxPUB02a6/d3Rh78InZldkJzcKLR8zM="
  # https://esphome.io/components/sensor/hlw8012.html
  voltage_divider: "2401"
  current_multiply: "1"

packages: !include common/devices/efun_sh331w.yaml
