# :07:FA:46
substitutions:
  device_name: bedroom-floor-light
  friendly_name: Bedroom Floor Light
  device_description: Bedroom Floor Light (Plug)
  ip_address: 10.0.65.140
  # fold -bw32 </dev/urandom|head -n1|tr -d '\n'|base64
  api_key: "sTgEqOW5xeK0UclVyMgoGizK4q47odAfNkZOdHscnLE="
  # https://esphome.io/components/sensor/hlw8012.html
  voltage_divider: "2401"
  current_multiply: "1"

packages:
  monoprice_stitch_35511: !include common/devices/monoprice_stitch_35511.yaml
