# 24:d7:eb:5a:3f:80
substitutions:
  device_name: bedroom-rgb-bulb
  friendly_name: Bedroom RGB Bulb
  device_description: ""
  ip_address: 10.0.65.161
  # fold -bw32 </dev/urandom|head -n1|tr -d '\n'|base64
  api_key: "RLmkkts97jChaka0hJRus58BN62HQkXgZskiiCSalxo="

packages:
  wyze_wlpa19c: !include common/devices/wyze_wlpa19c.yaml
