# 78:e3:6d:f7:be:c8
substitutions:
  device_name: living-room-rgb-bulb
  friendly_name: Living Room RGB Bulb
  device_description: ${friendly_name}
  ip_address: 10.0.65.162
  # fold -bw32 </dev/urandom|head -n1|tr -d '\n'|base64
  api_key: "9BrGmWgqzGEzg6Xi7tGgWiy9/nm5NaqyrpPmI9REVd8="

packages:
  wyze_wlpa19c: !include common/devices/wyze_wlpa19c.yaml
