substitutions:
  device_name: "avery-cube"
  friendly_name: "AveryCube"
  device_description: "Avery's Chemistry Cube"
  ip_address: "10.0.65.178"
  api_key: "7orNpqsb1GpxOyx+8qsT3zm/eLE3SHXoUa0IcLPjOMQ="

packages:
  - !include common/devices/m5stack-atom-lite.yaml

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG
  logs:
    sensor: INFO

i2c:
  - id: bus_grove
    sda: GPIO26
    scl: GPIO32
    scan: True
    frequency: 100kHz

sensor:
  - platform: kmeteriso
    i2c_id: bus_grove
    temperature:
      id: reactor_temp
      name: Reactor Temp
      on_value:
        - uart.write: !lambda char buf[128];
                      sprintf(buf, "T:%.1f\n", id(reactor_temp).state);
                      std::string s = buf;
                      return std::vector<unsigned char>( s.begin(), s.end() );
    internal_temperature:
      name: Meter Temp
    update_interval: 0.25s
  - platform: tmp1826
    address: 0xce87dc3047ca2f26
    name: "Condenser Inlet Temp"
    id: condenser_inlet_temp
    update_interval: 1s
  - platform: tmp1826
    address: 0xac6eb03047ca2f26
    name: "Condenser Outlet Temp"
    id: condenser_outlet_temp
    update_interval: 1s
  - platform: tmp1826
    address: 0xef4e8c3047ca2f26
    name: "Onewire Temp 2"
    id: onew_temp2
    update_interval: 1s
  - platform: tmp1826
    address: 0x923c383047ca2f26
    name: "Suction Temp"
    id: suction_temp
    update_interval: 1s
  - platform: tmp1826
    address: 0x563b763047ca2f26
    name: "Evaporator Temp"
    id: evaporator_temp
    update_interval: 1s

uart:
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3
  
one_wire:
  - platform: ds2484
    active_pullup: true
