# EFUN SH331W smart outlet

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0
  level: INFO

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

# Anti-lockout:
# Some devices can't be opened to reflash, so start AP mode
# unless explicitly disabled
wifi:
  ap:
    ssid: ESPHome ${friendly_name}
    password: !secret wifi_ap_password
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
    manual_ip:
      static_ip: ${ip_address}
      gateway: 10.0.65.1
      subnet: 255.255.255.0
      dns1: 10.0.65.1
  fast_connect: True

ota:
  platform: esphome
  password: !secret api_password

api:
  encryption:
    key: ${api_key}
